### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jcheng5** [ablakey/Leaflet.SimpleGraticule#5]
Hi there, I'd like to use your SimpleGraticule plugin, but I can't unless you attach a license to your project by putting a LICENSE file in your root directory.

If you don't have a strong opinion about [what license to choose](http://choosealicense.com/), you might consider using the one that Leaflet itself uses, the BSD 2-Clause (similar to MIT in that it's very simple and permissive):

https://github.com/Leaflet/Leaflet/blob/master/LICENSE

You'd just need to change the Copyright statements in the beginning to the appropriate name(s) and years.

Thank you for your consideration!

**Comment by ablakey** [comment]
Hi:

I've added a BSD license identical to what Leaflet uses.  Thanks for making it so easy to do so with your succinct description of what to do.
