### ISSUE TITLE
Leaflet 1.0 no longer uses 'clickable' in options.

### ISSUE THREAD

**Issue by JrFolk** [ablakey/Leaflet.SimpleGraticule#8]
Filing for later.

[The default `lineStyle.clickable`](https://github.com/ablakey/Leaflet.SimpleGraticule/blob/master/L.SimpleGraticule.js#L20)  should be changed from `clickable` to `interactive`.

At the moment there seems to be no reason why both can't exist be there.

[Here is my proposed change.](https://github.com/ablakey/Leaflet.SimpleGraticule/compare/master...JrFolk:patch-1)

**Comment by ablakey** [comment]
This looks good.  If you've tested it in both 0.7.* and 1.0 then I'm happy to merge this asap.  The only item is to add a space before the "legacy support" comment.  

Thank you for raising the issue.

**Comment by JrFolk** [comment]
We can close this :)

**Comment by ablakey** [comment]
Oops! Missed this step as I merged from bed on a phone :p
